category: string
logs_folder: string
file_path: string
analysis:
  tester_2d: boolean
  ball_possession: boolean
  foul_charge: boolean
  playmodes: boolean
  ball_history: boolean
  penalty: boolean
  passing_accuracy: boolean
  corners_occurrencies: boolean
  tester_free_kick: boolean
  intercept_counter: boolean
  stamina: boolean
  time_after_events: boolean
  heatmap: boolean
  shooting: boolean
  speed: boolean
  find_goals: boolean
  goalkeeper: boolean
  kick_in: boolean
  kick_in_occurrences: boolean