category: ssl
logs_folder: path/to/unified/logs
file_path: /home/emilly/github/SoccerAnalyzer/socceranalyzer/objPositions.csv
analysis:
  tester_2d: false
  ball_possession: false
  foul_charge: false
  playmodes: false
  ball_history: false
  penalty: false
  passing_accuracy: false
  corners_occurrencies: false
  tester_free_kick: false
  intercept_counter: false
  stamina: false
  time_after_events: false
  heatmap: true
  shooting: false
  speed: false
  find_goals: false
  goalkeeper: false